# Generated by Django 6.0.1 on 2026-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kasb',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
